spring:
  datasource:
    url: jdbc:mysql://192.168.10.102:32306/task
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  kafka:
    bootstrap-servers: 192.168.10.102:30901, 192.168.10.102:30902, 192.168.10.102:30903
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 335554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      transaction-id-prefix: kafka-tr-
      properties:
        "[enable.idempotence]": true
        "[transactional.id]": tran-id-1
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 100
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      isolation-level: read_committed
logging:
  level:
    org.springframework.transaction: trace
    org.springframework.kafka.transaction: debug